def func():
    try:
        print('try')
    except ValueError as e:
        print('error')
